version: '3.1'

services:

  caddy:
    image: "abiosoft/caddy:${CADDY_VERSION}"
    entrypoint: /usr/bin/caddy
    command: ["-conf", "/etc/caddy/Caddyfile", "-agree", "-ca", "https://acme-staging-v02.api.letsencrypt.org/directory"]
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:rw
      - ./config/ssl:/ssl:rw
      - ./log/caddy:/etc/caddy/logs:rw
    environment:
      TZ: ${TZ}
    restart: always
    networks:
      - frontend
      - backend

  avatar-cache:
    image: "idawnlight/avatar-cache:${AVATAR_CACHE_VERSION}"
    volumes:
      - ./cache:/www/cache:rw
      - ./config/config.php:/www/config.php:rw
    environment:
      TZ: ${TZ}
    restart: always
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge